# fly.toml app configuration file generated for still-star-3630 on 2023-09-19T23:10:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-star-3630"
primary_region = "phx"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
